"""init schema

Revision ID: 2b6e1046540a
Revises: 
Create Date: 2026-01-04 13:37:21.511405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b6e1046540a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spray_logs')
    op.drop_index(op.f('ix_chat_sessions_farm_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('scouting_logs')
    op.drop_table('brix_samples')
    op.drop_table('crop_status')
    op.drop_table('blocks')
    op.drop_table('farms')
    op.drop_table('irrigation_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('irrigation_logs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('farm_id', sa.VARCHAR(), nullable=False),
    sa.Column('block_id', sa.VARCHAR(), nullable=True),
    sa.Column('irrigated_at', sa.DATETIME(), nullable=False),
    sa.Column('amount_mm', sa.FLOAT(), nullable=True),
    sa.Column('duration_min', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farms',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('lat', sa.FLOAT(), nullable=False),
    sa.Column('lon', sa.FLOAT(), nullable=False),
    sa.Column('country_code', sa.VARCHAR(), nullable=True),
    sa.Column('preferred_language', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blocks',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('farm_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('variety', sa.VARCHAR(), nullable=True),
    sa.Column('planting_year', sa.INTEGER(), nullable=True),
    sa.Column('soil_type', sa.VARCHAR(), nullable=True),
    sa.Column('irrigation_type', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crop_status',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('farm_id', sa.VARCHAR(), nullable=False),
    sa.Column('block_id', sa.VARCHAR(), nullable=True),
    sa.Column('recorded_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('stage', sa.VARCHAR(), nullable=False),
    sa.Column('sweetness_brix', sa.FLOAT(), nullable=True),
    sa.Column('cracking', sa.BOOLEAN(), nullable=True),
    sa.Column('sunburn', sa.BOOLEAN(), nullable=True),
    sa.Column('mildew_signs', sa.BOOLEAN(), nullable=True),
    sa.Column('botrytis_signs', sa.BOOLEAN(), nullable=True),
    sa.Column('pest_signs', sa.BOOLEAN(), nullable=True),
    sa.Column('last_irrigation', sa.VARCHAR(), nullable=True),
    sa.Column('last_spray', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brix_samples',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('farm_id', sa.VARCHAR(), nullable=False),
    sa.Column('block_id', sa.VARCHAR(), nullable=True),
    sa.Column('sampled_at', sa.DATETIME(), nullable=False),
    sa.Column('brix', sa.FLOAT(), nullable=False),
    sa.Column('firmness_score', sa.INTEGER(), nullable=True),
    sa.Column('berry_size_mm', sa.FLOAT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scouting_logs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('farm_id', sa.VARCHAR(), nullable=False),
    sa.Column('block_id', sa.VARCHAR(), nullable=True),
    sa.Column('observed_at', sa.DATETIME(), nullable=False),
    sa.Column('photo_path', sa.VARCHAR(), nullable=True),
    sa.Column('issue_type', sa.VARCHAR(), nullable=False),
    sa.Column('severity', sa.INTEGER(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('farm_id', sa.VARCHAR(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('farm_id', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_farm_id'), 'chat_sessions', ['farm_id'], unique=False)
    op.create_table('spray_logs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('farm_id', sa.VARCHAR(), nullable=False),
    sa.Column('block_id', sa.VARCHAR(), nullable=True),
    sa.Column('sprayed_at', sa.DATETIME(), nullable=False),
    sa.Column('product_name', sa.VARCHAR(), nullable=True),
    sa.Column('target_issue', sa.VARCHAR(), nullable=True),
    sa.Column('phi_days', sa.INTEGER(), nullable=True),
    sa.Column('rei_hours', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
